# Generated by Django 2.1 on 2019-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.IntegerField(max_length=5),
        ),
    ]
