# Generated by Django 2.1 on 2019-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0002_auto_20190201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.IntegerField(),
        ),
    ]
